name: simple_gradient_text
description: Create fast and simple gradient texts, whether linear or radial, you just decide the colors and the text to display, very easy.
version: 1.2.2
repository: https://github.com/astudilloalex/flutter_gradient_text 

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: